import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CommonNavBar from "@/components/CommonNavBar";
import CommonFooter from "@/components/CommonFooter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * The root layout of the application.
 *
 * This component renders the root `<html>` and `<body>` elements, along with the
 * `<CommonNavBar />` and `<CommonFooter />` components. It also sets up the
 * font styles for the application.
 *
 * @param {{ children: React.ReactNode }} props The props object, containing the
 * children to render.
 * @returns The root layout of the application.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CommonNavBar />
        {children}
        <CommonFooter />
      </body>
    </html>
  );
}
